### ISSUE TITLE
It will not work with "Edge Translate"

### ISSUE THREAD

**Issue by canbus** [ArshSB/DarkPDF#5] opened 2022-09-17 08:57 UTC
I use DarkPdf to darken the pdf file in Chrome.
I only use DarkPdf is work perfect.The pdf is white on black.
But also use "Edge Translate",the DarkPdf  is not working.The pdf is black on white,not white on black

"Edge Translate" is a extension of chrome.(https://github.com/EdgeTranslate/EdgeTranslate)

**Comment by canbus** [comment] 2022-09-17 09:01
At last,I solve the problem:
Only use "Edge Translate",use below code in chrome's console to darken the pdf file
```
var cover = document.createElement("div");
let css = `
    position: fixed;
    pointer-events: none;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background-color: white;
    mix-blend-mode: difference;
    z-index: 1;
`
cover.setAttribute("style", css);
document.body.appendChild(cover);
```

but  this method is too cumbersome

**Comment by ArshSB** [comment] 2022-09-17 19:27
Hi Canbus,

I tried to reproduce this issue by installing the EdgeTranslate extension. It seems that this extension uses a different PDF viewer than the default viewer on Chrome/Edge browser. I also noticed that it already had dark mode enabled. Unfortunately, since DarkPDF is built for the default viewer, it may not work for the non-default ones and so it is beyond the scope of the extension. 

I'm glad you were able to find a solution to your problem though! I'll be closing this issue soon, thank you for using DarkPDF!

**Closed as completed** 2022-09-18 16:20 UTC
